FROM rust:latest as build

WORKDIR /app

COPY . .

RUN cp /app/crt/*.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
RUN rustup target add aarch64-unknown-linux-musl 
RUN rustup toolchain install stable-aarch64-unknown-linux-musl
RUN apt-get update && apt-get install -y musl-tools
RUN cargo build --release --target aarch64-unknown-linux-musl